export default function Documentation() {
  return (
    <div className="p-8 max-w-4xl mx-auto space-y-8 py-20 pb-40">
      <h1 className="font-heading text-4xl font-bold tracking-tight">Platform Documentation</h1>
      <div className="prose prose-lg dark:prose-invert max-w-none">
        
        <h2>Overview</h2>
        <p>SignalStack uses custom heuristic mapping overlaid on top of Google's Gemini models to ensure structured, highly-deterministic outputs from unstructured business systems.</p>

        <h2>Data Preparation</h2>
        <p>For the best analytical results, ensure your data conforms to the following standards before upload:</p>
        
        <h3>1. Meeting Transcripts (TXT, VTT, MD)</h3>
        <ul>
          <li><strong>Speaker attribution is required:</strong> `Elena: I think we should...`</li>
          <li><strong>Timestamps are optional</strong> but improve timeline visualization.</li>
          <li>Scrub personally identifiable information (PII) before uploading.</li>
        </ul>

        <h3>2. Support Tickets / Refund Logs (CSV)</h3>
        <p>Minimum required columns:</p>
        <pre>Ticket_ID, Customer_Segment, Ticket_Body, Resolution_Status</pre>

        <h3>3. Sequence Uploads</h3>
        <p>When using the Narrative Drift Tracker, files must be named sequentially (e.g., `1_Q1.txt`, `2_Q2.txt`) to establish chronological order.</p>

        <h2>Interpreting AI Confidence Scores</h2>
        <p>Every insight generated by SignalStack is assigned a confidence/risk score (0-100%).</p>
        <ul>
          <li><strong>High Risk (80-100%):</strong> Explicit contradictions found. Direct action required.</li>
          <li><strong>Moderate Risk (40-79%):</strong> Ambiguous language or partial gaps. Escalate for clarification.</li>
          <li><strong>Low Risk (0-39%):</strong> Total semantic alignment across sources.</li>
        </ul>

        <hr className="my-8" />
        
        <p className="text-sm text-muted-foreground">For API integration docs, please contact your account manager to enable the Webhook Early Access feature.</p>

      </div>
    </div>
  );
}
